from .base import DbCommitedEntity

from .absen import DbAbsen
from .angsuran import DbAngsuran
from .departemen import DbDepartemen
from .jabatan import DbJabatan
from .jenis_angsuran import DbJenisAngsuran
from .job_level import DbJobLevel
from .karyawan import DbKaryawan
from .kinerja import DbKinerja
from .lembur import DbLembur
from .masa_kerja import DbMasaKerja
from .pengaturan import DbPengaturan
from .periode_gaji import DbPeriodeGaji
from .perusahaan import DbPerusahaan
from .shift import DbShift
from .subdepartemen import DbSubdepartemen
from .tunjangan_khusus import DbTunjanganKhusus
from .tunjangan_kinerja import DbTunjanganKinerja
from .tunjangan_masa_kerja import DbTunjanganMasaKerja
