#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:package_prefix=rpc.gen.
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import rpc.gen.user.main.ttypes
import rpc.gen.hello.main.ttypes
import rpc.gen.file.main.ttypes
import rpc.gen.system.main.ttypes

from thrift.transport import TTransport
all_structs = []
fix_spec(all_structs)
del all_structs
